### ISSUE TITLE
Keeps saving to SVG and not PNG

### ISSUE THREAD

**Issue by AACCBB80** [alexharris/ditherit-v2#17]
When you are done using the converter and try to download it, it downloads as an SVG but is encoded as a PNG.

**Comment by alexharris** [comment]
Hi @AACCBB80 - can  you tell me a little bit more about what behavior you are taking to see this result? When you press the save button to download the file, you end up with an SVG with a .png extension? Can you include one of these files in your response, I'd love to take a look at it.

thanks!

**Comment by AACCBB80** [comment]
What I mean is that when the image is saved the SVG extension is used instead of the PNG extension on images that have the .png.svg extension.
Dithered Image
![dither_it_1200px-SMPTE_Color_Bars](https://user-images.githubusercontent.com/89084279/152173986-7d622b50-2701-44d3-a878-be379709c17c.svg)
Original image
https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/SMPTE_Color_Bars.svg/1280px-SMPTE_Color_Bars.svg.png

**Comment by alexharris** [comment]
When I upload that image, dither it, and then save, the file that I download is a PNG with the filename "1280px-SMPTE_Color_Bars.svg.png". You are saying that when you download it, it just has ".svg" at the end, and no ".png" after that?

Can you tell me what browser you are using?

**Comment by AACCBB80** [comment]
Yes
Browser:
Google Chrome 98.0.4758.82 (Official Build) (64-bit)

**Comment by alexharris** [comment]
I just tried it in Chrome and I was able to successfully download a png as expected. Hmmm...

**Comment by AACCBB80** [comment]
It might be a problem on my end, and I just tried ti and it seems fine. I don't know what went wrong. Thanks for helping though!

**Comment by alexharris** [comment]
OK thanks! let me know if it pops back up
