### ISSUE TITLE
Uncaught TypeError: "width" is read-only

### ISSUE THREAD

**Issue by Metaln00b** [alexharris/ditherit-v2#23]
Hello, 
I have a problem when dithering. I want to dither a 128x296 PNG.

Thank you.
![image](https://user-images.githubusercontent.com/25951169/197869029-49fa2f25-a038-47b0-a0cd-0428f6a4dfb6.png)

**Comment by atc1441** [comment]
Something did broke for me as well with the latest updates.
Dithering never finishes with the same error

**Comment by alexharris** [comment]
Hi, ok...I just did some updates and it looks like something broke. Looking into it now!

**Comment by atc1441** [comment]
Thanks its working again with the newest updates to change it to a var :)

**Comment by alexharris** [comment]
@Metaln00b @atc1441 Yep, should be fixed now! Thanks for reporting the bug.

**Comment by atc1441** [comment]
Sending you a coffee now :)

**Comment by alexharris** [comment]
@atc1441 oops good idea. Just turned paypal on

**Comment by alexharris** [comment]
Thanks @atc1441  I actually do need a coffee after breaking everything this morning ha. thanks for using dither it!

**Comment by Metaln00b** [comment]
@alexharris Thank you for ditherit and fixing the problem so fast :P

**Comment by atc1441** [comment]
@alexharris Thank you as well for making it!

To advertise at least a bit i am ( and also @Metaln00b ) is using it for some old "hacked" e-paper price tags :)

Its just impressive to see what is possible with just 3 colors!
![20221025_224839](https://user-images.githubusercontent.com/1102694/197879288-176846df-61da-48c6-bb7e-e08395a9f149.jpg)

See more infos here: https://youtu.be/98fOzZs__fc

**Comment by alexharris** [comment]
Super cool! thanks for sharing
