### ISSUE TITLE
what's more between implement details and standard methods?

### ISSUE THREAD

**Issue by vraivon** [alexharris/ditherit-v2#4]
I implemented a version of burkes dither with python, but when testing the same image, i found that the effect was quite different from your algorithm,and your result looked better. so i wanted to know what else besides the basic error diffusion op? and why?

Thx

**Comment by alexharris** [comment]
Hi vraivon,

The actual dithering is done using the [rgbquant.js library](https://github.com/leeoniya/RgbQuant.js). That code is pretty reasonable so you might find some luck there. There are also quite a few options that ditherit does not expose to the user such histogram method, number of hues, dithering threshold, etc. You can see the rgbquant defaults on that page, or you can see the defaults that Dither it! uses here: https://github.com/alexharris/ditherit-v2/blob/cc7876ad55539821a216ed0163e62aebb96e7ce5/pages/index.vue#L422

Hope that helps!

**Comment by vraivon** [comment]
@alexharris thank you!
