### ISSUE TITLE
Serpentine option: span should be label

### ISSUE THREAD

**Issue by cadars** [alexharris/ditherit-v2#7]
https://github.com/alexharris/ditherit-v2/blob/1647ff1be30709f0e0d3ad4dc2d6a65372ab4403/pages/index.vue#L140

Linked to the checkbox `id` so `<label for="id">` can act as a button.

**Comment by alexharris** [comment]
Good call, this has been fixed [here](https://github.com/alexharris/ditherit-v2/commit/16d831ecf60f49e0cda683695d68ab52a341930f#diff-02281a80fab758cb4e8e8359b222a8a5afeaa9d5a7ba858f15d852f1f8969ecf). Thanks for mentioning, @cadars!
