### ISSUE TITLE
Drag & drop image

### ISSUE THREAD

**Issue by timotheegoguely** [alexharris/ditherit-v2#8]
Feature suggestion: improve UX by allowing to drag any compatible image directly to a drop zone on the homepage, a bit like squoosh.app do.

**Comment by alexharris** [comment]
@timotheegoguely hello, I have had this feature on my to-do list for a long time, so thank you for finally giving me some motivation to do it. I have implemented the feature, and have it up on a dev build here: https://hardcore-lalande-d5454b.netlify.app/

If you have any time to do a little testing, please feel free to do so. Either way, I will deploy it to the main site soon, but the earlier I can catch any bugs the better!

The only functionality is:

1. Allows for multiple images to be dragged at once
2. Makes sure all files are either a png, jpg, or gif
3. Hidden on mobile

**Comment by alexharris** [comment]
deployed!
